### ISSUE TITLE
データを Pickle で送ろうとするとクライアントがコケる

### ISSUE THREAD

**Issue by hoto17296** [hoto17296/asyncio-practice#1]
``` diff
diff --git a/janken/message.py b/janken/message.py
index 9ffd599..734b486 100644
--- a/janken/message.py
+++ b/janken/message.py
@@ -1,5 +1,5 @@
 import re
-import json
+import pickle
 import asyncio
 from pyee import EventEmitter

@@ -22,19 +22,15 @@ class MessageConnection(EventEmitter):
     def send(self, event, *args, **kwargs):
         assert(self.writer)
         assert(type(event) is str and re.compile(r'^\w+$').match(event))
-        message = '%s\t%s\n' % (event, json.dumps([args, kwargs]))
-        self.writer.write(message.encode())
+        message = pickle.dumps((event, args, kwargs)) + b'\n'
+        self.writer.write(message)

     async def listen(self):
         assert(self.reader)
-        pattern = re.compile(r'^(\w+?)\t(.*)\n$')
         while True:
             message = await self.reader.readline()
             if message:
-                matched = pattern.match(message.decode())
-                assert(matched)
-                event, data = matched.groups()
-                args, kwargs = json.loads(data)
+                event, args, kwargs = pickle.loads(message)
                 self.emit(event, *args, **kwargs)
             else:
                 self.emit('disconnect')
```

```
Traceback (most recent call last):
  File "janken/client.py", line 41, in <module>
    loop.run_until_complete(connection.connect('localhost', 8888))
  File "~/.anyenv/envs/pyenv/versions/3.6.1/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "asyncio-practice/janken/message.py", line 20, in connect
    await self.listen()
  File "asyncio-practice/janken/message.py", line 33, in listen
    event, args, kwargs = pickle.loads(message)
EOFError: Ran out of input
```

**Comment by hoto17296** [comment]
サーバもエラー出る

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<MessageServer.handler() done, defined at asyncio-practice/janken/message.py:48> exception=UnpicklingError('pickle data was truncated',)>
Traceback (most recent call last):
  File "asyncio-practice/janken/message.py", line 51, in handler
    self.emit('connect', connection)
  File "asyncio-practice/janken/message.py", line 33, in listen
    print(message)
_pickle.UnpicklingError: pickle data was truncated
```
